# Generated by Django 5.2.1 on 2025-05-23 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_content_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date']},
        ),
    ]
