# Generated by Django 5.2.1 on 2025-05-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_communityquestion_communityanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community_images/', verbose_name='Görsel'),
        ),
    ]
