# Generated by Django 5.2.1 on 2025-05-23 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='article.comment', verbose_name='Yanıtlanan Yorum'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Yanıtlanan Kullanıcı'),
        ),
    ]
