"""
Django settings for DjangoBlog project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import dotenv
from dotenv import load_dotenv

# WASI ortamında USER environment variable gerekli (PyMySQL için)
if 'USER' not in os.environ:
    os.environ['USER'] = 'app'
if 'LOGNAME' not in os.environ:
    os.environ['LOGNAME'] = 'app'

# PyMySQL'i mysqlclient yerine kullan (Wasmer Edge WASI uyumluluğu için)
try:
    import pymysql
    pymysql.install_as_MySQLdb()
    PYMYSQL_AVAILABLE = True
except (ImportError, Exception):
    PYMYSQL_AVAILABLE = False

load_dotenv()

TOGETHER_API_KEY = os.getenv("TOGETHER_API_KEY")


from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fallback-key-change-in-production-12345')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = [
    'codenthia-com.onrender.com', 
    'codenthia-blog.wasmer.app',  # Wasmer Edge domain (tire ile)
    'codenthia_blog.wasmer.app',  # Alt çizgi versiyonu
    '.wasmer.app',  # Tüm Wasmer subdomainleri
    '*',  # Geçici olarak tüm hostlara izin ver (debug için)
    'localhost', 
    '127.0.0.1'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "article", # Bu kod, article uygulamasını projenin diğer bölümlerine entegre eder
    "user",
    'ckeditor', # Zengin metin editörü için eklendi
    'django_cleanup.apps.CleanupConfig', # Bu kod, Django'nun dosya silme işlemlerini otomatikleştirir
    'chatbot',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DjangoBlog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["templates"], # Bu kod, Django'ya şablon dosyalarının bulunduğu dizini belirtir
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# Custom error pages
handler404 = 'article.views.handler404' # Bu kod, 404 hatasının oluştuğu zaman hangi sayfaya yönlendirileceğini belirtir

WSGI_APPLICATION = 'DjangoBlog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Wasmer Edge MySQL veya local SQLite
# PyMySQL mevcut ve DB_HOST tanımlıysa MySQL kullan, değilse SQLite
if os.getenv('DB_HOST') and PYMYSQL_AVAILABLE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USERNAME'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT', '3306'),
            'OPTIONS': {
                'charset': 'utf8mb4',
            }
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # Bu kod, static dosyalarının toplanacağı dizini belirtir


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Media dosyalarını serve etmek için güvenlik ayarı
X_FRAME_OPTIONS = 'SAMEORIGIN'
SECURE_CONTENT_TYPE_NOSNIFF = False  # Media dosyaları için gerekli

CKEDITOR_CONFIGS = {
    'default': {
        'removePlugins': 'stylesheetparser',
        'allowedContent': True,
        'width': '100%',

}
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

CSRF_COOKIE_SECURE = False  # Test için False, üretimde True yapın
SESSION_COOKIE_SECURE = False  # Test için False, üretimde True yapın

# WASI/h11 uyumluluğu için CSRF token'ı session'da sakla (cookie header sorunu)
CSRF_USE_SESSIONS = True

CSRF_TRUSTED_ORIGINS = [
    'https://codenthia-com.onrender.com',
    'https://codenthia-blog.wasmer.app',  # Tire ile (URL'deki gibi)
    'https://codenthia_blog.wasmer.app',  # Alt çizgi versiyonu
    'https://*.wasmer.app',
]